今回はアルゴリズムの説明はQiitaに書きました。  
markdownでまとめる方が楽でして。。。  

https://qiita.com/Rowing0914/items/e0fee727cf761458d2f7

## 実装

### 一回のみ重み更新パーセプトロンの実装

In [87]:
import numpy as np

def perceptron(X, W, theta, result):
    for i in X:
        z = np.dot(W.T, i)
        if z >= theta:
            print("z: %.3f, result: %d" % (z, 1))
            result.append(1)
        else:
            print("z: %.3f, result: %d" % (z, 0))
            result.append(0)
    return result

def update_rule(X, y, prediction, learning_rate, W):
    index = 0
    for label, pred in zip(y, prediction):
        error = label - pred
        update_value = (learning_rate*error)*X[index].reshape(3,1)
        W += update_value
        index+=1
    return W

# dataset
X = np.random.rand(10, 3)
y = np.random.randint(0, 2, size=(10,1))

# weight vector
W = np.random.uniform(low=0, high=1, size=(3,1))

# theta, threshold
theta = 0.5
result = []

prediction = perceptron(X, W, theta, result)

# list => numpy arrayの変換
prediction = np.array(prediction).reshape(len(prediction),1)

# 学習率
learning_rate = 0.02

print("更新前の重み\n",W)

# 重みの更新
W = update_rule(X, y, prediction, learning_rate, W)
print("重みを一回だけ更新後\n",W)


z: 0.193, result: 0
z: 0.653, result: 1
z: 0.035, result: 0
z: 0.431, result: 0
z: 0.533, result: 1
z: 0.425, result: 0
z: 0.341, result: 0
z: 0.612, result: 1
z: 0.506, result: 1
z: 0.374, result: 0
更新前の重み
 [[ 0.17032679]
 [ 0.48175616]
 [ 0.28825018]]
重みを一回だけ更新後
 [[ 0.19292359]
 [ 0.4968191 ]
 [ 0.31667254]]


In [109]:
import numpy as np

def perceptron(X, W, theta, result):
    for i in X:
        z = np.dot(W.T, i)
        if z >= theta:
            print("z: %.3f, result: %d" % (z, 1))
            result.append(1)
        else:
            print("z: %.3f, result: %d" % (z, 0))
            result.append(0)
    return result

def update_rule(X, y, prediction, learning_rate, W):
    index = 0
    errors = []
    for label, pred in zip(y, prediction):
        error = label - pred
        update_value = (learning_rate*error)*X[index].reshape(3,1)
        W += update_value
        index+=1
        errors.append(error)
    # 何個間違っているのかを計算する
    num_error = np.abs(sum(errors))
    return W, num_error

# dataset
X = np.random.rand(10, 3)
y = np.random.randint(0, 2, size=(10,1))

# weight vector
W = np.random.uniform(low=0, high=1, size=(3,1))

# theta, threshold
theta = 0.5
result = []

# 学習率
learning_rate = 0.002

print("更新前の重み\n",W)

# 重みの更新
while True:
    prediction = perceptron(X, W, theta, result)
    # list => numpy arrayの変換
    prediction = np.array(prediction).reshape(len(prediction),1)
    W, num_error = update_rule(X, y, prediction, learning_rate, W)
    print("重み更新後\n",W)
    print(num_error)

    # 間違いの数を閾値とする
    if num_error <= 3:
        break


更新前の重み
 [[ 0.12769556]
 [ 0.13866919]
 [ 0.21994058]]
z: 0.228, result: 0
z: 0.230, result: 0
z: 0.310, result: 0
z: 0.238, result: 0
z: 0.209, result: 0
z: 0.122, result: 0
z: 0.312, result: 0
z: 0.183, result: 0
z: 0.312, result: 0
z: 0.308, result: 0
重み更新後
 [[ 0.13451872]
 [ 0.14440234]
 [ 0.22689454]]
[6]
z: 0.238, result: 0
z: 0.239, result: 0
z: 0.323, result: 0
z: 0.248, result: 0
z: 0.218, result: 0
z: 0.128, result: 0
z: 0.324, result: 0
z: 0.191, result: 0
z: 0.325, result: 0
z: 0.320, result: 0
重み更新後
 [[ 0.14134188]
 [ 0.15013548]
 [ 0.23384851]]
[6]
z: 0.247, result: 0
z: 0.249, result: 0
z: 0.336, result: 0
z: 0.257, result: 0
z: 0.226, result: 0
z: 0.133, result: 0
z: 0.335, result: 0
z: 0.199, result: 0
z: 0.337, result: 0
z: 0.331, result: 0
重み更新後
 [[ 0.14816503]
 [ 0.15586863]
 [ 0.24080247]]
[6]
z: 0.257, result: 0
z: 0.258, result: 0
z: 0.349, result: 0
z: 0.266, result: 0
z: 0.235, result: 0
z: 0.138, result: 0
z: 0.347, result: 0
z: 0.206, result: 0
z: 0.349, resul

[6]
z: 0.802, result: 1
z: 0.799, result: 1
z: 1.100, result: 1
z: 0.808, result: 1
z: 0.735, result: 1
z: 0.436, result: 0
z: 1.040, result: 1
z: 0.651, result: 1
z: 1.064, result: 1
z: 0.995, result: 1
重み更新後
 [[ 0.55073129]
 [ 0.49412427]
 [ 0.6510863 ]]
[6]
z: 0.811, result: 1
z: 0.809, result: 1
z: 1.113, result: 1
z: 0.817, result: 1
z: 0.744, result: 1
z: 0.441, result: 0
z: 1.052, result: 1
z: 0.658, result: 1
z: 1.076, result: 1
z: 1.007, result: 1
重み更新後
 [[ 0.55755444]
 [ 0.49985741]
 [ 0.65804027]]
[6]
z: 0.821, result: 1
z: 0.818, result: 1
z: 1.126, result: 1
z: 0.827, result: 1
z: 0.752, result: 1
z: 0.446, result: 0
z: 1.064, result: 1
z: 0.666, result: 1
z: 1.088, result: 1
z: 1.018, result: 1
重み更新後
 [[ 0.5643776 ]
 [ 0.50559056]
 [ 0.66499423]]
[6]
z: 0.830, result: 1
z: 0.827, result: 1
z: 1.139, result: 1
z: 0.836, result: 1
z: 0.761, result: 1
z: 0.451, result: 0
z: 1.075, result: 1
z: 0.674, result: 1
z: 1.101, result: 1
z: 1.029, result: 1
重み更新後
 [[ 0.57120076]
 [ 

z: 0.996, result: 1
z: 2.341, result: 1
z: 1.486, result: 1
z: 2.407, result: 1
z: 2.223, result: 1
重み更新後
 [[ 1.29445539]
 [ 1.11903722]
 [ 1.4090683 ]]
[6]
z: 1.836, result: 1
z: 1.826, result: 1
z: 2.524, result: 1
z: 1.835, result: 1
z: 1.684, result: 1
z: 1.001, result: 1
z: 2.353, result: 1
z: 1.493, result: 1
z: 2.419, result: 1
z: 2.234, result: 1
重み更新後
 [[ 1.30127854]
 [ 1.12477037]
 [ 1.41602226]]
[6]
z: 1.846, result: 1
z: 1.835, result: 1
z: 2.537, result: 1
z: 1.844, result: 1
z: 1.693, result: 1
z: 1.006, result: 1
z: 2.365, result: 1
z: 1.501, result: 1
z: 2.431, result: 1
z: 2.246, result: 1
重み更新後
 [[ 1.3081017 ]
 [ 1.13050352]
 [ 1.42297622]]
[6]
z: 1.855, result: 1
z: 1.845, result: 1
z: 2.550, result: 1
z: 1.854, result: 1
z: 1.701, result: 1
z: 1.011, result: 1
z: 2.377, result: 1
z: 1.509, result: 1
z: 2.443, result: 1
z: 2.257, result: 1
重み更新後
 [[ 1.31492486]
 [ 1.13623666]
 [ 1.42993019]]
[6]
z: 1.864, result: 1
z: 1.854, result: 1
z: 2.563, result: 1
z: 1.863, re

 [[ 2.03817948]
 [ 1.74395018]
 [ 2.16705029]]
[6]
z: 2.861, result: 1
z: 2.844, result: 1
z: 3.935, result: 1
z: 2.853, result: 1
z: 2.624, result: 1
z: 1.561, result: 1
z: 3.654, result: 1
z: 2.328, result: 1
z: 3.762, result: 1
z: 3.462, result: 1
重み更新後
 [[ 2.04500264]
 [ 1.74968333]
 [ 2.17400426]]
[6]
z: 2.871, result: 1
z: 2.853, result: 1
z: 3.948, result: 1
z: 2.862, result: 1
z: 2.633, result: 1
z: 1.566, result: 1
z: 3.666, result: 1
z: 2.336, result: 1
z: 3.774, result: 1
z: 3.473, result: 1
重み更新後
 [[ 2.0518258 ]
 [ 1.75541647]
 [ 2.18095822]]
[6]
z: 2.880, result: 1
z: 2.862, result: 1
z: 3.961, result: 1
z: 2.871, result: 1
z: 2.641, result: 1
z: 1.571, result: 1
z: 3.678, result: 1
z: 2.343, result: 1
z: 3.786, result: 1
z: 3.485, result: 1
重み更新後
 [[ 2.05864895]
 [ 1.76114962]
 [ 2.18791218]]
[6]
z: 2.889, result: 1
z: 2.872, result: 1
z: 3.974, result: 1
z: 2.881, result: 1
z: 2.650, result: 1
z: 1.576, result: 1
z: 3.689, result: 1
z: 2.351, result: 1
z: 3.799, result: 

重み更新後
 [[ 2.75461095]
 [ 2.34593055]
 [ 2.89721643]]
[6]
z: 3.848, result: 1
z: 3.824, result: 1
z: 5.294, result: 1
z: 3.833, result: 1
z: 3.530, result: 1
z: 2.100, result: 1
z: 4.907, result: 1
z: 3.133, result: 1
z: 5.055, result: 1
z: 4.645, result: 1
重み更新後
 [[ 2.76143411]
 [ 2.3516637 ]
 [ 2.9041704 ]]
[6]
z: 3.858, result: 1
z: 3.833, result: 1
z: 5.307, result: 1
z: 3.843, result: 1
z: 3.538, result: 1
z: 2.105, result: 1
z: 4.919, result: 1
z: 3.140, result: 1
z: 5.067, result: 1
z: 4.656, result: 1
重み更新後
 [[ 2.76825727]
 [ 2.35739684]
 [ 2.91112436]]
[6]
z: 3.867, result: 1
z: 3.842, result: 1
z: 5.320, result: 1
z: 3.852, result: 1
z: 3.547, result: 1
z: 2.110, result: 1
z: 4.931, result: 1
z: 3.148, result: 1
z: 5.080, result: 1
z: 4.667, result: 1
重み更新後
 [[ 2.77508042]
 [ 2.36312999]
 [ 2.91807832]]
[6]
z: 3.877, result: 1
z: 3.852, result: 1
z: 5.333, result: 1
z: 3.861, result: 1
z: 3.556, result: 1
z: 2.115, result: 1
z: 4.943, result: 1
z: 3.155, result: 1
z: 5.092, re

z: 4.075, result: 1
z: 6.570, result: 1
z: 6.030, result: 1
重み更新後
 [[ 3.6006824 ]
 [ 3.0568407 ]
 [ 3.75950788]]
[6]
z: 5.014, result: 1
z: 4.981, result: 1
z: 6.899, result: 1
z: 4.991, result: 1
z: 4.599, result: 1
z: 2.737, result: 1
z: 6.387, result: 1
z: 4.082, result: 1
z: 6.583, result: 1
z: 6.042, result: 1
重み更新後
 [[ 3.60750556]
 [ 3.06257385]
 [ 3.76646184]]
[6]
z: 5.024, result: 1
z: 4.991, result: 1
z: 6.912, result: 1
z: 5.000, result: 1
z: 4.608, result: 1
z: 2.742, result: 1
z: 6.399, result: 1
z: 4.090, result: 1
z: 6.595, result: 1
z: 6.053, result: 1
重み更新後
 [[ 3.61432872]
 [ 3.068307  ]
 [ 3.7734158 ]]
[6]
z: 5.033, result: 1
z: 5.000, result: 1
z: 6.925, result: 1
z: 5.010, result: 1
z: 4.617, result: 1
z: 2.747, result: 1
z: 6.411, result: 1
z: 4.098, result: 1
z: 6.607, result: 1
z: 6.064, result: 1
重み更新後
 [[ 3.62115187]
 [ 3.07404014]
 [ 3.78036977]]
[6]
z: 5.043, result: 1
z: 5.009, result: 1
z: 6.938, result: 1
z: 5.019, result: 1
z: 4.625, result: 1
z: 2.752, re

 [[ 4.41263807]
 [ 3.73908513]
 [ 4.58702951]]
[6]
z: 6.133, result: 1
z: 6.092, result: 1
z: 8.440, result: 1
z: 6.102, result: 1
z: 5.626, result: 1
z: 3.348, result: 1
z: 7.807, result: 1
z: 4.994, result: 1
z: 8.049, result: 1
z: 7.382, result: 1
重み更新後
 [[ 4.41946123]
 [ 3.74481827]
 [ 4.59398347]]
[6]
z: 6.143, result: 1
z: 6.101, result: 1
z: 8.453, result: 1
z: 6.112, result: 1
z: 5.634, result: 1
z: 3.353, result: 1
z: 7.819, result: 1
z: 5.002, result: 1
z: 8.061, result: 1
z: 7.393, result: 1
重み更新後
 [[ 4.42628438]
 [ 3.75055142]
 [ 4.60093743]]
[6]
z: 6.152, result: 1
z: 6.111, result: 1
z: 8.466, result: 1
z: 6.121, result: 1
z: 5.643, result: 1
z: 3.359, result: 1
z: 7.831, result: 1
z: 5.009, result: 1
z: 8.073, result: 1
z: 7.404, result: 1
重み更新後
 [[ 4.43310754]
 [ 3.75628457]
 [ 4.6078914 ]]
[6]
z: 6.162, result: 1
z: 6.120, result: 1
z: 8.479, result: 1
z: 6.130, result: 1
z: 5.652, result: 1
z: 3.364, result: 1
z: 7.843, result: 1
z: 5.017, result: 1
z: 8.086, result: 

重み更新後
 [[ 5.1836548 ]
 [ 4.38693067]
 [ 5.37282735]]
[6]
z: 7.196, result: 1
z: 7.147, result: 1
z: 9.903, result: 1
z: 7.157, result: 1
z: 6.600, result: 1
z: 3.929, result: 1
z: 9.156, result: 1
z: 5.860, result: 1
z: 9.441, result: 1
z: 8.655, result: 1
重み更新後
 [[ 5.19047795]
 [ 4.39266381]
 [ 5.37978132]]
[6]
z: 7.205, result: 1
z: 7.156, result: 1
z: 9.916, result: 1
z: 7.167, result: 1
z: 6.609, result: 1
z: 3.934, result: 1
z: 9.168, result: 1
z: 5.867, result: 1
z: 9.453, result: 1
z: 8.666, result: 1
重み更新後
 [[ 5.19730111]
 [ 4.39839696]
 [ 5.38673528]]
[6]
z: 7.215, result: 1
z: 7.166, result: 1
z: 9.928, result: 1
z: 7.176, result: 1
z: 6.618, result: 1
z: 3.939, result: 1
z: 9.180, result: 1
z: 5.875, result: 1
z: 9.465, result: 1
z: 8.677, result: 1
重み更新後
 [[ 5.20412427]
 [ 4.40413011]
 [ 5.39368924]]
[6]
z: 7.224, result: 1
z: 7.175, result: 1
z: 9.941, result: 1
z: 7.185, result: 1
z: 6.626, result: 1
z: 3.944, result: 1
z: 9.192, result: 1
z: 5.883, result: 1
z: 9.478, re

z: 4.535, result: 1
z: 10.565, result: 1
z: 6.763, result: 1
z: 10.894, result: 1
z: 9.984, result: 1
重み更新後
 [[ 5.99561046]
 [ 5.06917509]
 [ 6.20034898]]
[6]
z: 8.315, result: 1
z: 8.258, result: 1
z: 11.443, result: 1
z: 8.269, result: 1
z: 7.627, result: 1
z: 4.540, result: 1
z: 10.576, result: 1
z: 6.771, result: 1
z: 10.907, result: 1
z: 9.995, result: 1
重み更新後
 [[ 6.00243362]
 [ 5.07490824]
 [ 6.20730294]]
[6]
z: 8.324, result: 1
z: 8.267, result: 1
z: 11.456, result: 1
z: 8.278, result: 1
z: 7.635, result: 1
z: 4.545, result: 1
z: 10.588, result: 1
z: 6.779, result: 1
z: 10.919, result: 1
z: 10.006, result: 1
重み更新後
 [[ 6.00925678]
 [ 5.08064138]
 [ 6.21425691]]
[6]
z: 8.334, result: 1
z: 8.276, result: 1
z: 11.469, result: 1
z: 8.287, result: 1
z: 7.644, result: 1
z: 4.550, result: 1
z: 10.600, result: 1
z: 6.786, result: 1
z: 10.931, result: 1
z: 10.018, result: 1
重み更新後
 [[ 6.01607993]
 [ 5.08637453]
 [ 6.22121087]]
[6]
z: 8.343, result: 1
z: 8.286, result: 1
z: 11.482, result: 

z: 5.115, result: 1
z: 11.913, result: 1
z: 7.629, result: 1
z: 12.286, result: 1
z: 11.257, result: 1
重み更新後
 [[ 6.76662719]
 [ 5.71702063]
 [ 6.98614683]]
[6]
z: 9.377, result: 1
z: 9.313, result: 1
z: 12.906, result: 1
z: 9.324, result: 1
z: 8.602, result: 1
z: 5.120, result: 1
z: 11.925, result: 1
z: 7.637, result: 1
z: 12.299, result: 1
z: 11.268, result: 1
重み更新後
 [[ 6.77345034]
 [ 5.72275378]
 [ 6.99310079]]
[6]
z: 9.387, result: 1
z: 9.322, result: 1
z: 12.919, result: 1
z: 9.333, result: 1
z: 8.610, result: 1
z: 5.126, result: 1
z: 11.937, result: 1
z: 7.644, result: 1
z: 12.311, result: 1
z: 11.279, result: 1
重み更新後
 [[ 6.7802735 ]
 [ 5.72848692]
 [ 7.00005476]]
[6]
z: 9.396, result: 1
z: 9.331, result: 1
z: 12.932, result: 1
z: 9.342, result: 1
z: 8.619, result: 1
z: 5.131, result: 1
z: 11.949, result: 1
z: 7.652, result: 1
z: 12.323, result: 1
z: 11.291, result: 1
重み更新後
 [[ 6.78709666]
 [ 5.73422007]
 [ 7.00700872]]
[6]
z: 9.405, result: 1
z: 9.341, result: 1
z: 12.945, result

z: 10.421, result: 1
z: 10.349, result: 1
z: 14.343, result: 1
z: 10.360, result: 1
z: 9.559, result: 1
z: 5.691, result: 1
z: 13.250, result: 1
z: 8.487, result: 1
z: 13.666, result: 1
z: 12.518, result: 1
重み更新後
 [[ 7.53082076]
 [ 6.35913303]
 [ 7.76499071]]
[6]
z: 10.430, result: 1
z: 10.358, result: 1
z: 14.356, result: 1
z: 10.370, result: 1
z: 9.568, result: 1
z: 5.696, result: 1
z: 13.262, result: 1
z: 8.495, result: 1
z: 13.678, result: 1
z: 12.530, result: 1
重み更新後
 [[ 7.53764391]
 [ 6.36486617]
 [ 7.77194468]]
[6]
z: 10.440, result: 1
z: 10.367, result: 1
z: 14.369, result: 1
z: 10.379, result: 1
z: 9.576, result: 1
z: 5.701, result: 1
z: 13.274, result: 1
z: 8.502, result: 1
z: 13.691, result: 1
z: 12.541, result: 1
重み更新後
 [[ 7.54446707]
 [ 6.37059932]
 [ 7.77889864]]
[6]
z: 10.449, result: 1
z: 10.377, result: 1
z: 14.382, result: 1
z: 10.388, result: 1
z: 9.585, result: 1
z: 5.706, result: 1
z: 13.286, result: 1
z: 8.510, result: 1
z: 13.703, result: 1
z: 12.552, result: 1
重

 [[ 8.20631329]
 [ 6.92671452]
 [ 8.45343308]]
[6]
z: 11.361, result: 1
z: 11.282, result: 1
z: 15.637, result: 1
z: 11.294, result: 1
z: 10.421, result: 1
z: 6.204, result: 1
z: 14.444, result: 1
z: 9.253, result: 1
z: 14.898, result: 1
z: 13.645, result: 1
重み更新後
 [[ 8.21313644]
 [ 6.93244767]
 [ 8.46038704]]
[6]
z: 11.371, result: 1
z: 11.292, result: 1
z: 15.650, result: 1
z: 11.303, result: 1
z: 10.430, result: 1
z: 6.209, result: 1
z: 14.456, result: 1
z: 9.261, result: 1
z: 14.910, result: 1
z: 13.656, result: 1
重み更新後
 [[ 8.2199596 ]
 [ 6.93818081]
 [ 8.467341  ]]
[6]
z: 11.380, result: 1
z: 11.301, result: 1
z: 15.663, result: 1
z: 11.313, result: 1
z: 10.439, result: 1
z: 6.215, result: 1
z: 14.468, result: 1
z: 9.268, result: 1
z: 14.922, result: 1
z: 13.667, result: 1
重み更新後
 [[ 8.22678276]
 [ 6.94391396]
 [ 8.47429497]]
[6]
z: 11.389, result: 1
z: 11.310, result: 1
z: 15.676, result: 1
z: 11.322, result: 1
z: 10.447, result: 1
z: 6.220, result: 1
z: 14.479, result: 1
z: 9.276

[6]
z: 12.424, result: 1
z: 12.337, result: 1
z: 17.100, result: 1
z: 12.349, result: 1
z: 11.396, result: 1
z: 6.785, result: 1
z: 15.792, result: 1
z: 10.119, result: 1
z: 16.290, result: 1
z: 14.917, result: 1
重み更新後
 [[ 8.98415317]
 [ 7.58029321]
 [ 9.24618489]]
[6]
z: 12.433, result: 1
z: 12.346, result: 1
z: 17.113, result: 1
z: 12.359, result: 1
z: 11.405, result: 1
z: 6.790, result: 1
z: 15.804, result: 1
z: 10.126, result: 1
z: 16.302, result: 1
z: 14.929, result: 1
重み更新後
 [[ 8.99097632]
 [ 7.58602636]
 [ 9.25313885]]
[6]
z: 12.443, result: 1
z: 12.356, result: 1
z: 17.126, result: 1
z: 12.368, result: 1
z: 11.413, result: 1
z: 6.795, result: 1
z: 15.816, result: 1
z: 10.134, result: 1
z: 16.315, result: 1
z: 14.940, result: 1
重み更新後
 [[ 8.99779948]
 [ 7.5917595 ]
 [ 9.26009282]]
[6]
z: 12.452, result: 1
z: 12.365, result: 1
z: 17.139, result: 1
z: 12.377, result: 1
z: 11.422, result: 1
z: 6.800, result: 1
z: 15.828, result: 1
z: 10.142, result: 1
z: 16.327, result: 1
z: 14.951,

重み更新後
 [[ 9.5641215 ]
 [ 8.06761065]
 [ 9.83727177]]
[6]
z: 13.232, result: 1
z: 13.140, result: 1
z: 18.214, result: 1
z: 13.152, result: 1
z: 12.138, result: 1
z: 7.226, result: 1
z: 16.819, result: 1
z: 10.777, result: 1
z: 17.349, result: 1
z: 15.886, result: 1
重み更新後
 [[ 9.57094466]
 [ 8.0733438 ]
 [ 9.84422573]]
[6]
z: 13.242, result: 1
z: 13.149, result: 1
z: 18.227, result: 1
z: 13.162, result: 1
z: 12.147, result: 1
z: 7.232, result: 1
z: 16.831, result: 1
z: 10.785, result: 1
z: 17.362, result: 1
z: 15.897, result: 1
重み更新後
 [[ 9.57776781]
 [ 8.07907695]
 [ 9.85117969]]
[6]
z: 13.251, result: 1
z: 13.158, result: 1
z: 18.239, result: 1
z: 13.171, result: 1
z: 12.155, result: 1
z: 7.237, result: 1
z: 16.843, result: 1
z: 10.793, result: 1
z: 17.374, result: 1
z: 15.909, result: 1
重み更新後
 [[ 9.58459097]
 [ 8.08481009]
 [ 9.85813366]]
[6]
z: 13.261, result: 1
z: 13.168, result: 1
z: 18.252, result: 1
z: 13.180, result: 1
z: 12.164, result: 1
z: 7.242, result: 1
z: 16.855, result: 1

z: 13.070, result: 1
z: 7.781, result: 1
z: 18.108, result: 1
z: 11.605, result: 1
z: 18.680, result: 1
z: 17.103, result: 1
重み更新後
 [[ 10.3078456 ]
 [  8.69252361]
 [ 10.59525376]]
[6]
z: 14.257, result: 1
z: 14.157, result: 1
z: 19.625, result: 1
z: 14.170, result: 1
z: 13.078, result: 1
z: 7.786, result: 1
z: 18.120, result: 1
z: 11.612, result: 1
z: 18.692, result: 1
z: 17.114, result: 1
重み更新後
 [[ 10.31466876]
 [  8.69825676]
 [ 10.60220772]]
[6]
z: 14.267, result: 1
z: 14.167, result: 1
z: 19.638, result: 1
z: 14.179, result: 1
z: 13.087, result: 1
z: 7.791, result: 1
z: 18.132, result: 1
z: 11.620, result: 1
z: 18.704, result: 1
z: 17.125, result: 1
重み更新後
 [[ 10.32149191]
 [  8.7039899 ]
 [ 10.60916169]]
[6]
z: 14.276, result: 1
z: 14.176, result: 1
z: 19.650, result: 1
z: 14.189, result: 1
z: 13.095, result: 1
z: 7.797, result: 1
z: 18.144, result: 1
z: 11.628, result: 1
z: 18.717, result: 1
z: 17.136, result: 1
重み更新後
 [[ 10.32831507]
 [  8.70972305]
 [ 10.61611565]]
[6]
z: 14.28

z: 12.478, result: 1
z: 20.084, result: 1
z: 18.387, result: 1
重み更新後
 [[ 11.08568548]
 [  9.3461023 ]
 [ 11.38800557]]
[6]
z: 15.329, result: 1
z: 15.221, result: 1
z: 21.100, result: 1
z: 15.235, result: 1
z: 14.061, result: 1
z: 8.372, result: 1
z: 19.481, result: 1
z: 12.486, result: 1
z: 20.096, result: 1
z: 18.398, result: 1
重み更新後
 [[ 11.09250864]
 [  9.35183545]
 [ 11.39495954]]
[6]
z: 15.339, result: 1
z: 15.231, result: 1
z: 21.113, result: 1
z: 15.244, result: 1
z: 14.070, result: 1
z: 8.377, result: 1
z: 19.493, result: 1
z: 12.493, result: 1
z: 20.109, result: 1
z: 18.409, result: 1
重み更新後
 [[ 11.09933179]
 [  9.35756859]
 [ 11.4019135 ]]
[6]
z: 15.348, result: 1
z: 15.240, result: 1
z: 21.126, result: 1
z: 15.253, result: 1
z: 14.079, result: 1
z: 8.382, result: 1
z: 19.504, result: 1
z: 12.501, result: 1
z: 20.121, result: 1
z: 18.420, result: 1
重み更新後
 [[ 11.10615495]
 [  9.36330174]
 [ 11.40886746]]
[6]
z: 15.357, result: 1
z: 15.249, result: 1
z: 21.139, result: 1
z: 15.2

z: 16.260, result: 1
z: 16.146, result: 1
z: 22.382, result: 1
z: 16.159, result: 1
z: 14.915, result: 1
z: 8.880, result: 1
z: 20.662, result: 1
z: 13.244, result: 1
z: 21.316, result: 1
z: 19.513, result: 1
重み更新後
 [[ 11.76800117]
 [  9.91941694]
 [ 12.0834019 ]]
[6]
z: 16.270, result: 1
z: 16.155, result: 1
z: 22.395, result: 1
z: 16.168, result: 1
z: 14.924, result: 1
z: 8.886, result: 1
z: 20.674, result: 1
z: 13.252, result: 1
z: 21.328, result: 1
z: 19.524, result: 1
重み更新後
 [[ 11.77482432]
 [  9.92515009]
 [ 12.09035586]]
[6]
z: 16.279, result: 1
z: 16.164, result: 1
z: 22.408, result: 1
z: 16.178, result: 1
z: 14.933, result: 1
z: 8.891, result: 1
z: 20.686, result: 1
z: 13.259, result: 1
z: 21.341, result: 1
z: 19.536, result: 1
重み更新後
 [[ 11.78164748]
 [  9.93088323]
 [ 12.09730982]]
[6]
z: 16.288, result: 1
z: 16.174, result: 1
z: 22.421, result: 1
z: 16.187, result: 1
z: 14.941, result: 1
z: 8.896, result: 1
z: 20.698, result: 1
z: 13.267, result: 1
z: 21.353, result: 1
z: 19

 [ 12.75098237]]
[6]
z: 17.172, result: 1
z: 17.051, result: 1
z: 23.638, result: 1
z: 17.065, result: 1
z: 15.752, result: 1
z: 9.379, result: 1
z: 21.820, result: 1
z: 13.987, result: 1
z: 22.511, result: 1
z: 20.606, result: 1
重み更新後
 [[ 12.42984738]
 [ 10.47553214]
 [ 12.75793633]]
[6]
z: 17.182, result: 1
z: 17.060, result: 1
z: 23.651, result: 1
z: 17.074, result: 1
z: 15.761, result: 1
z: 9.384, result: 1
z: 21.832, result: 1
z: 13.995, result: 1
z: 22.523, result: 1
z: 20.617, result: 1
重み更新後
 [[ 12.43667054]
 [ 10.48126529]
 [ 12.7648903 ]]
[6]
z: 17.191, result: 1
z: 17.070, result: 1
z: 23.664, result: 1
z: 17.083, result: 1
z: 15.769, result: 1
z: 9.389, result: 1
z: 21.844, result: 1
z: 14.002, result: 1
z: 22.536, result: 1
z: 20.628, result: 1
重み更新後
 [[ 12.4434937 ]
 [ 10.48699843]
 [ 12.77184426]]
[6]
z: 17.200, result: 1
z: 17.079, result: 1
z: 23.677, result: 1
z: 17.093, result: 1
z: 15.778, result: 1
z: 9.394, result: 1
z: 21.856, result: 1
z: 14.010, result: 1
z: 22

[6]
z: 18.225, result: 1
z: 18.097, result: 1
z: 25.088, result: 1
z: 18.110, result: 1
z: 16.718, result: 1
z: 9.954, result: 1
z: 23.157, result: 1
z: 14.845, result: 1
z: 23.891, result: 1
z: 21.867, result: 1
重み更新後
 [[ 13.19404095]
 [ 11.11764454]
 [ 13.53678022]]
[6]
z: 18.235, result: 1
z: 18.106, result: 1
z: 25.101, result: 1
z: 18.120, result: 1
z: 16.727, result: 1
z: 9.959, result: 1
z: 23.169, result: 1
z: 14.853, result: 1
z: 23.903, result: 1
z: 21.878, result: 1
重み更新後
 [[ 13.20086411]
 [ 11.12337768]
 [ 13.54373418]]
[6]
z: 18.244, result: 1
z: 18.115, result: 1
z: 25.113, result: 1
z: 18.129, result: 1
z: 16.735, result: 1
z: 9.964, result: 1
z: 23.181, result: 1
z: 14.860, result: 1
z: 23.915, result: 1
z: 21.890, result: 1
重み更新後
 [[ 13.20768726]
 [ 11.12911083]
 [ 13.55068814]]
[6]
z: 18.253, result: 1
z: 18.125, result: 1
z: 25.126, result: 1
z: 18.139, result: 1
z: 16.744, result: 1
z: 9.969, result: 1
z: 23.193, result: 1
z: 14.868, result: 1
z: 23.928, result: 1
z

z: 19.156, result: 1
z: 19.021, result: 1
z: 26.369, result: 1
z: 19.035, result: 1
z: 17.572, result: 1
z: 10.463, result: 1
z: 24.339, result: 1
z: 15.603, result: 1
z: 25.110, result: 1
z: 22.982, result: 1
重み更新後
 [[ 13.86953348]
 [ 11.68522603]
 [ 14.22522258]]
[6]
z: 19.166, result: 1
z: 19.030, result: 1
z: 26.382, result: 1
z: 19.044, result: 1
z: 17.581, result: 1
z: 10.468, result: 1
z: 24.350, result: 1
z: 15.611, result: 1
z: 25.123, result: 1
z: 22.994, result: 1
重み更新後
 [[ 13.87635664]
 [ 11.69095918]
 [ 14.23217654]]
[6]
z: 19.175, result: 1
z: 19.039, result: 1
z: 26.395, result: 1
z: 19.054, result: 1
z: 17.589, result: 1
z: 10.473, result: 1
z: 24.362, result: 1
z: 15.619, result: 1
z: 25.135, result: 1
z: 23.005, result: 1
重み更新後
 [[ 13.88317979]
 [ 11.69669232]
 [ 14.23913051]]
[6]
z: 19.184, result: 1
z: 19.049, result: 1
z: 26.408, result: 1
z: 19.063, result: 1
z: 17.598, result: 1
z: 10.478, result: 1
z: 24.374, result: 1
z: 15.626, result: 1
z: 25.147, result: 1
z

z: 10.940, result: 1
z: 25.449, result: 1
z: 16.316, result: 1
z: 26.256, result: 1
z: 24.030, result: 1
重み更新後
 [[ 14.50408707]
 [ 12.21840864]
 [ 14.87194116]]
[6]
z: 20.040, result: 1
z: 19.898, result: 1
z: 27.586, result: 1
z: 19.913, result: 1
z: 18.383, result: 1
z: 10.945, result: 1
z: 25.460, result: 1
z: 16.323, result: 1
z: 26.268, result: 1
z: 24.041, result: 1
重み更新後
 [[ 14.51091022]
 [ 12.22414179]
 [ 14.87889513]]
[6]
z: 20.049, result: 1
z: 19.907, result: 1
z: 27.599, result: 1
z: 19.922, result: 1
z: 18.391, result: 1
z: 10.950, result: 1
z: 25.472, result: 1
z: 16.331, result: 1
z: 26.280, result: 1
z: 24.052, result: 1
重み更新後
 [[ 14.51773338]
 [ 12.22987494]
 [ 14.88584909]]
[6]
z: 20.059, result: 1
z: 19.917, result: 1
z: 27.612, result: 1
z: 19.931, result: 1
z: 18.400, result: 1
z: 10.956, result: 1
z: 25.484, result: 1
z: 16.339, result: 1
z: 26.293, result: 1
z: 24.064, result: 1
重み更新後
 [[ 14.52455654]
 [ 12.23560808]
 [ 14.89280305]]
[6]
z: 20.068, result: 1
z: 1

 [[ 15.21369538]
 [ 12.81465587]
 [ 15.59515334]]
[6]
z: 21.018, result: 1
z: 20.869, result: 1
z: 28.932, result: 1
z: 20.884, result: 1
z: 19.280, result: 1
z: 11.480, result: 1
z: 26.702, result: 1
z: 17.120, result: 1
z: 27.549, result: 1
z: 25.213, result: 1
重み更新後
 [[ 15.22051854]
 [ 12.82038902]
 [ 15.60210731]]
[6]
z: 21.027, result: 1
z: 20.878, result: 1
z: 28.945, result: 1
z: 20.893, result: 1
z: 19.288, result: 1
z: 11.485, result: 1
z: 26.714, result: 1
z: 17.128, result: 1
z: 27.562, result: 1
z: 25.224, result: 1
重み更新後
 [[ 15.2273417 ]
 [ 12.82612216]
 [ 15.60906127]]
[6]
z: 21.037, result: 1
z: 20.888, result: 1
z: 28.958, result: 1
z: 20.902, result: 1
z: 19.297, result: 1
z: 11.490, result: 1
z: 26.726, result: 1
z: 17.135, result: 1
z: 27.574, result: 1
z: 25.235, result: 1
重み更新後
 [[ 15.23416485]
 [ 12.83185531]
 [ 15.61601523]]
[6]
z: 21.046, result: 1
z: 20.897, result: 1
z: 28.971, result: 1
z: 20.912, result: 1
z: 19.306, result: 1
z: 11.495, result: 1
z: 26.738,

z: 21.690, result: 1
z: 30.072, result: 1
z: 21.705, result: 1
z: 20.039, result: 1
z: 11.932, result: 1
z: 27.752, result: 1
z: 17.794, result: 1
z: 28.633, result: 1
z: 26.204, result: 1
重み更新後
 [[ 15.82095634]
 [ 13.3249059 ]
 [ 16.21405607]]
[6]
z: 21.855, result: 1
z: 21.700, result: 1
z: 30.085, result: 1
z: 21.715, result: 1
z: 20.047, result: 1
z: 11.937, result: 1
z: 27.764, result: 1
z: 17.802, result: 1
z: 28.646, result: 1
z: 26.215, result: 1
重み更新後
 [[ 15.8277795 ]
 [ 13.33063904]
 [ 16.22101004]]
[6]
z: 21.864, result: 1
z: 21.709, result: 1
z: 30.097, result: 1
z: 21.724, result: 1
z: 20.056, result: 1
z: 11.942, result: 1
z: 27.776, result: 1
z: 17.810, result: 1
z: 28.658, result: 1
z: 26.226, result: 1
重み更新後
 [[ 15.83460266]
 [ 13.33637219]
 [ 16.227964  ]]
[6]
z: 21.874, result: 1
z: 21.718, result: 1
z: 30.110, result: 1
z: 21.733, result: 1
z: 20.065, result: 1
z: 11.947, result: 1
z: 27.788, result: 1
z: 17.817, result: 1
z: 28.670, result: 1
z: 26.238, result: 1
重

z: 31.353, result: 1
z: 22.630, result: 1
z: 20.893, result: 1
z: 12.440, result: 1
z: 28.934, result: 1
z: 18.553, result: 1
z: 29.853, result: 1
z: 27.319, result: 1
重み更新後
 [[ 16.49644887]
 [ 13.89248739]
 [ 16.90249844]]
[6]
z: 22.786, result: 1
z: 22.624, result: 1
z: 31.366, result: 1
z: 22.639, result: 1
z: 20.901, result: 1
z: 12.445, result: 1
z: 28.946, result: 1
z: 18.560, result: 1
z: 29.865, result: 1
z: 27.330, result: 1
重み更新後
 [[ 16.50327203]
 [ 13.89822054]
 [ 16.9094524 ]]
[6]
z: 22.795, result: 1
z: 22.633, result: 1
z: 31.379, result: 1
z: 22.649, result: 1
z: 20.910, result: 1
z: 12.450, result: 1
z: 28.958, result: 1
z: 18.568, result: 1
z: 29.878, result: 1
z: 27.341, result: 1
重み更新後
 [[ 16.51009519]
 [ 13.90395368]
 [ 16.91640636]]
[6]
z: 22.804, result: 1
z: 22.643, result: 1
z: 31.392, result: 1
z: 22.658, result: 1
z: 20.919, result: 1
z: 12.456, result: 1
z: 28.970, result: 1
z: 18.576, result: 1
z: 29.890, result: 1
z: 27.353, result: 1
重み更新後
 [[ 16.51691834]

z: 30.032, result: 1
z: 19.257, result: 1
z: 30.986, result: 1
z: 28.355, result: 1
重み更新後
 [[ 17.1241793 ]
 [ 14.41993686]
 [ 17.54226305]]
[6]
z: 23.651, result: 1
z: 23.483, result: 1
z: 32.557, result: 1
z: 23.498, result: 1
z: 21.695, result: 1
z: 12.918, result: 1
z: 30.044, result: 1
z: 19.265, result: 1
z: 30.999, result: 1
z: 28.366, result: 1
重み更新後
 [[ 17.13100246]
 [ 14.42567001]
 [ 17.54921702]]
[6]
z: 23.660, result: 1
z: 23.492, result: 1
z: 32.570, result: 1
z: 23.508, result: 1
z: 21.704, result: 1
z: 12.923, result: 1
z: 30.056, result: 1
z: 19.273, result: 1
z: 31.011, result: 1
z: 28.378, result: 1
重み更新後
 [[ 17.13782562]
 [ 14.43140315]
 [ 17.55617098]]
[6]
z: 23.669, result: 1
z: 23.501, result: 1
z: 32.583, result: 1
z: 23.517, result: 1
z: 21.712, result: 1
z: 12.928, result: 1
z: 30.068, result: 1
z: 19.280, result: 1
z: 31.023, result: 1
z: 28.389, result: 1
重み更新後
 [[ 17.14464877]
 [ 14.4371363 ]
 [ 17.56312494]]
[6]
z: 23.679, result: 1
z: 23.511, result: 1
z: 3

KeyboardInterrupt: 