今回はアルゴリズムの説明はQiitaに書きました。  
markdownでまとめる方が楽でして。。。  

https://qiita.com/Rowing0914/items/e0fee727cf761458d2f7

## 実装

### 一回のみ重み更新パーセプトロンの実装

In [2]:
X

array([[0.3588434 , 0.34525849, 0.06141849],
       [0.29575676, 0.3524059 , 0.01935928],
       [0.10469905, 0.72790586, 0.32933082],
       [0.52217517, 0.5597451 , 0.26956989],
       [0.69246189, 0.95598998, 0.910297  ],
       [0.14931409, 0.36465034, 0.68482533],
       [0.30090531, 0.28241025, 0.43610198],
       [0.81582506, 0.12471843, 0.15490734],
       [0.21242529, 0.06979104, 0.84312058],
       [0.23295057, 0.24231447, 0.2136989 ]])

In [6]:
import numpy as np

def perceptron(X, W, theta, result):
    for i in X:
        z = np.dot(W.T, i)
        if z >= theta:
            print("z: %.3f, result: %d" % (z, 1))
            result.append(1)
        else:
            print("z: %.3f, result: %d" % (z, 0))
            result.append(0)
    return result

def update_rule(X, y, prediction, learning_rate, W):
    index = 0
    for label, pred in zip(y, prediction):
        error = label - pred
        update_value = (learning_rate*error)*X[index].reshape(3,1)
        W += update_value
        index+=1
    return W

# dataset
X = np.random.rand(10, 3)
y = np.random.randint(0, 2, size=(10,1))

# weight vector
W = np.random.uniform(low=0, high=1, size=(3,1))

# theta, threshold
theta = 0.5
result = []

prediction = perceptron(X, W, theta, result)

# list => numpy arrayの変換
prediction = np.array(prediction).reshape(len(prediction),1)

# 学習率
learning_rate = 0.02

print("更新前の重み\n",W)

# 重みの更新
W = update_rule(X, y, prediction, learning_rate, W)
print("重みを一回だけ更新後\n",W)


z: 0.429, result: 0
z: 0.979, result: 1
z: 0.820, result: 1
z: 0.991, result: 1
z: 1.316, result: 1
z: 0.986, result: 1
z: 0.856, result: 1
z: 0.688, result: 1
z: 0.482, result: 0
z: 0.842, result: 1
更新前の重み
 [[0.33074942]
 [0.90893887]
 [0.33195033]]
重みを一回だけ更新後
 [[0.27555971]
 [0.83487793]
 [0.2583083 ]]


In [4]:
import numpy as np

def perceptron(X, W, theta, result):
    for i in X:
        z = np.dot(W.T, i)
        if z >= theta:
            print("z: %.3f, result: %d" % (z, 1))
            result.append(1)
        else:
            print("z: %.3f, result: %d" % (z, 0))
            result.append(0)
    return result

def update_rule(X, y, prediction, learning_rate, W):
    index = 0
    errors = []
    for label, pred in zip(y, prediction):
        error = label - pred
        update_value = (learning_rate*error)*X[index].reshape(3,1)
        W += update_value
        index+=1
        errors.append(error)
    # 何個間違っているのかを計算する
    num_error = np.abs(sum(errors))
    return W, num_error

# dataset
X = np.random.rand(10, 3)
y = np.random.randint(0, 2, size=(10,1))

# weight vector
W = np.random.uniform(low=0, high=1, size=(3,1))

# theta, threshold
theta = 0.5
result = []

# 学習率
learning_rate = 0.002

print("更新前の重み\n",W)

# 重みの更新
while True:
    prediction = perceptron(X, W, theta, result)
    # list => numpy arrayの変換
    prediction = np.array(prediction).reshape(len(prediction),1)
    W, num_error = update_rule(X, y, prediction, learning_rate, W)
    print("重み更新後\n",W)
    print(num_error)

    # 間違いの数を閾値とする
    if num_error <= 3:
        break


更新前の重み
 [[0.80372474]
 [0.16451678]
 [0.33784733]]
z: 0.582, result: 1
z: 0.674, result: 1
z: 0.846, result: 1
z: 0.446, result: 0
z: 0.094, result: 0
z: 0.360, result: 0
z: 0.257, result: 0
z: 0.937, result: 1
z: 0.603, result: 1
z: 0.298, result: 0
重み更新後
 [[0.80214373]
 [0.16497098]
 [0.33890637]]
[1]
